### ISSUE TITLE
Use uPickle for JSON serialization

### ISSUE THREAD

**Issue by kkasravi** [intel-hadoop/gearpump#178] opened 2014-11-27 16:46 UTC
[uPickle](https://github.com/lihaoyi/upickle) is a fast serde processor that also integrates with Scala.js. It allows AST integration with popular AST's including spray-json. Minimal dependencies - only jawn.

**Comment by clockfly** [comment] 2015-02-01 03:06
duplicate of #358

**Comment by clockfly** [comment] 2015-02-01 03:07
fixed in PR #384

**Closed by clockfly** 2015-02-01 03:06 UTC
