### ISSUE TITLE
Dynamic Graph Rewiring

### ISSUE THREAD

**Issue by sirinath** [intel-hadoop/gearpump#303] opened 2015-01-14 06:41 UTC
Is it possible to add support to dynamically rewire graph.

**Comment by clockfly** [comment] 2015-01-14 13:51
Can you elaborate more about the usage scenario?

**Comment by sirinath** [comment] 2015-01-14 14:03
This might be too simplistic but say we have historic data and live data. You can switch the source in runtime.

**Comment by kkasravi** [comment] 2015-01-14 17:43
Duplicate of #101

**Closed by kkasravi** 2015-01-14 17:43 UTC
Labels: duplicate
