### ISSUE TITLE
Support MillWheel-like User interface

### ISSUE THREAD

**Issue by whjiang** [intel-hadoop/gearpump#41] opened 2014-09-19 06:21 UTC
MillWheel support following user API:
```java
class Computation {
   void ProcessRecord(Record data);
   void ProcessTimer(Timer timer);

   void setTimer(String tag, int64 time);
   void ProduceRecord(Record data, String stream);

   StateType MutablePersistentState();
}
```
I think it is worthwhile to implement some similar interface for user to use. This can simplify usage.

**Comment by clockfly** [comment] 2015-07-04 05:59
duplicate of transactional API.

**Closed by clockfly** 2015-07-04 05:59 UTC
Labels: feature, P3
