### ISSUE TITLE
Many timeout related UT failures

### ISSUE THREAD

**Issue by kkasravi** [intel-hadoop/gearpump#1027] opened 2015-06-15 16:18 UTC
[Story](https://www.pivotaltracker.com/story/show/95597796)
[Parent Issue](https://github.com/intel-hadoop/gearpump/issues/970)
See follow up comments of various Travis build failures

**Comment by clockfly** [comment] 2015-07-10 13:37
fixed by https://github.com/intel-hadoop/gearpump/pull/1164

**Comment by clockfly** [comment] 2015-07-10 13:37
duplicate of #1165

**Closed** 2015-07-11 04:57 UTC
Labels: feature, UT
