### ISSUE TITLE
Allow adaptive cluster control

### ISSUE THREAD

**Issue by whjiang** [intel-hadoop/gearpump#15] opened 2014-08-26 07:07 UTC
It is better that if we can allow the number of executors (level of parallelism) dynamically adjustable. That is, application/framework can automatically adjust its parallelism based on input characteristics.

**Comment by clockfly** [comment] 2015-07-11 05:26
With dynamic dag, we can change the parallism.

Duplicate of #101

**Closed by clockfly** 2015-07-11 05:26 UTC
Labels: core, P3
