### ISSUE TITLE
No way for a TaskActor to cancel a subscription

### ISSUE THREAD

**Issue by kkasravi** [intel-hadoop/gearpump#297] opened 2015-01-13 21:19 UTC
This is part of #167
Currently TaskActors are configured within a DAG. This DAG is used by each publisher within its preStart method so that any call to output(...) will publish to all downstream subscribers. Should any Subscriber wish to cancel its subscription there is no way to do so. We should expose this functionality which will modify the DAG and runtime of the publishers.

**Comment by clockfly** [comment] 2015-07-04 05:58
duplicate of #101

**Closed by clockfly** 2015-07-04 05:58 UTC
Labels: core, P2
