### ISSUE TITLE
Migrate DAG API to Akka Streams API

### ISSUE THREAD

**Issue by sirinath** [intel-hadoop/gearpump#286] opened 2015-01-11 12:03 UTC
I think is is a win for the long run if the DAG API uses the Akka Streams for Graph and Partial Graphs with Gear Pump concentrating on distribution, clustering and scheduling of partial graph elements.

**Comment by kkasravi** [comment] 2015-01-11 12:18
Hi Suminda 

#167 is a similar issue I've opened and have been working on. However we're looking into implementing the reactive streams API rather than akka-streams. Currently the DSL's of GearPump and akka-streams are similar. There are some limitations of akka-streams (1.0-M2) related to performance. We'll keep this open to serve as a vehicle for discussion and will reference a design within this issue. Thanks.

**Comment by sirinath** [comment] 2015-01-11 13:03
I guess the performance issues may be addressed towards 1.0.

But having said that support for other reactive streams is much desirable.

**Comment by kkasravi** [comment] 2015-01-11 19:02
Thanks Suminda. There are some other concerns as well related to the rules
- we do not ack per message which can probably be addressed by ```Subscription.request(<big value>)```. Since this is how back pressure is applied the spec seems to be overloading concepts. Should a subscriber want to guarantee message receipt in this way (see [Subscriber controlled queue bounds](https://github.com/reactive-streams/reactive-streams)) it seems very inefficient - the publisher must call Subscriber.onComplete and the Subscriber must then resubmit a new subscription.
- the constraint that a publisher should only support one subscriber seems limiting. Although the spec allows for multi-subscribers (1.11).

An interesting read related to event processing is [here](https://groups.google.com/forum/#!topic/akka-user/MNDc9cVG1To)

**Comment by kkasravi** [comment] 2015-01-13 18:39
Rather than extend akka's implementation of Reactive Streams (1.0-M2), GearPump will implement the Reactive Streams API (1.0-M3). This means that GearPump will provide an additional actor based implementation of Reactive Streams that is specific to BigData requirements. I believe this is also what  [sirinath](https://github.com/sirinath) had suggested as desirable. Marking this as a duplicate of #167 and closing.

**Comment by kkasravi** [comment] 2015-01-13 18:40
See #167

**Closed by kkasravi** 2015-01-13 18:40 UTC
Labels: duplicate

**Comment by sirinath** [comment] 2015-01-14 04:32
If you create a flow graph or partial flow graph in Akka why not it be usable in GearPump?

**Comment by kkasravi** [comment] 2015-01-14 04:38
A FlowGraph or PartialFlowGraph is very specific to akka-streams and uses a very different model that requires an implicit Materializer and many other things that are not required if we're just implementing the ReactiveStreams API (1.0-M3).

We will provide this type of functionality within our DSL (where parts of a computation can be distributed to a remote actor and invoked). I think our DSL will be much simpler that what i currently see in akka-streams.

**Comment by sirinath** [comment] 2015-01-14 04:45
Give some functionality in GearPump where it will be easier to semalessly interop Akka Streams graphs along with you implimentation

**Comment by kkasravi** [comment] 2015-01-14 06:15
+1 - there will be value in doing that.
